# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# Commands to start on workspace startup
tasks:
  - name: Setup & Build
    before: npm install -g mocha
    init: cd server && npm install
