image:
  file: .gitpod.Dockerfile


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# Commands to start on workspace startup
tasks:
  - name: Setup & Build
    before: npm install -g mocha
    init: cd app && npm install && cd ../server && npm install
  - name: Setup fastAPI
    init: pip install -r api/requirements.txt
    command: echo 'start api'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: fastAPI ML server
    description: ML Server
    port: 8080
    onOpen: ignore
  - name: React App
    port: 3000
    onOpen: open-browser
  - name: Database Server
    port: 8000
    onOpen: ignore


# vscode:
#   extensions:
#     - ms-python.python
#     - entepe85.gitlens  
#     - esbenp.prettier-vscode